[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Crowded Discard Disable
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    if G.GAME.current_round.discards_left <= 0 or #G.hand.highlighted <= 0 then 
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''
position = 'after'
match_indent = true
payload = '''
    elseif G.bi_crowded_highlighted > 0 then
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''

# Crowded Play Disable
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > 5 then 
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''
position = 'after'
match_indent = true
payload = '''
    elseif G.bi_crowded_highlighted > 0 then
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''