[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Crowded Discard Disable
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = 'G.FUNCS.can_discard = function(e)'
position = 'before'
match_indent = true
payload = '''
    G.FUNCS.has_crowd = function()
        if #G.hand.highlighted > 0 then
            for i = 1, #G.hand.highlighted do
                if SMODS.has_enhancement(G.hand.highlighted[i], "m_bi_crowd") then
                    return true
                end
            end
        end
        return false
    end
'''

# Crowded Discard Disable
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    if G.GAME.current_round.discards_left <= 0 or #G.hand.highlighted <= 0 then 
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''
position = 'after'
match_indent = true
payload = '''
    elseif G.FUNCS.has_crowd() then
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''

# Crowded Play Disable
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    if #G.hand.highlighted <= 0 or G.GAME.blind.block_play or #G.hand.highlighted > 5 then 
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''
position = 'after'
match_indent = true
payload = '''
    elseif G.FUNCS.has_crowd() then
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
'''


